import sqlite3

#CONEXION CON LA BASE DE DATOS, SI NO EXISTE SE CREA.
conn = sqlite3.connect('..\sqlite\database_seguridad.db')
cursor = conn.cursor()

#CREACION DE LAS TABLAS
cursor.execute("CREATE TABLE USERS (USER_ID INTEGER PRIMARY KEY AUTOINCREMENT, USERNAME TEXT NOT NULL, PASSWORD TEXT NOT NULL);")
cursor.execute("CREATE TABLE ALERT_TYPE (ALERT_ID INTEGER PRIMARY KEY AUTOINCREMENT, DESCRIPTION TEXT NOT NULL);")
cursor.execute("CREATE TABLE ALERTS_REGISTRY (AR_ID INTEGER PRIMARY KEY AUTOINCREMENT, ALERT_ID INTEGER NOT NULL, SENSOR TEXT NOT NULL, ALERT_DATE TEXT NOT NULL, ALERT_TIME TEXT NOT NULL, FOREIGN KEY(ALERT_ID) REFERENCES ALERT_TYPE(ALERT_ID) );")
cursor.execute("CREATE TABLE CONNECTIONS (CONNECTION_ID INTEGER PRIMARY KEY AUTOINCREMENT, CONNECTION_DATE TEXT, CONNECTION_TIME TEXT);")

cursor.close()